### ISSUE TITLE
v4 upgrade ?

### ISSUE THREAD

**Issue by RoyiNamir** [NathanaelA/nativescript-orientation#28]
![image](https://user-images.githubusercontent.com/2842123/40809082-f1a873da-6531-11e8-9bc4-7881db93c5b3.png)

**Comment by NathanaelA** [comment]
LOL, guess that will teach me to lock it to 3.x...

**Comment by NathanaelA** [comment]
NativeScript Dom was locked to the peer depenancy; I have released v2.0.1 of it that removes that line...

**Comment by RoyiNamir** [comment]
@NathanaelA  Short question , isn't the red warning is under nativescript-orientation , however you did fixed DOM. , but looking at the tree it doesn't seems that the red section is a child of DOM , but a child of orienatation.

Am I looking at it wrongly ?

**Comment by NathanaelA** [comment]
To be honest your interpretation of the picture is correct, and that threw me initially too -- because when looking at the package for NS-Orientation, it didn't have a peer dependency on anything.   I knew I used it in one of my plugins when NS 3.x first came out, so it was a matter of looking at dependencies of NS-Orientation and seeing if they had peer set on them, and it ended up that NS-Dom was the culprit.   

My guess to why:
NPM saw NS-Orientation has a direct dependency on NS-Dom, and NS-Dom has a peer dependency of NS 3.x -- so after it listed all the normal deps it resolved; it then listed the peer' dep's...
