### ISSUE TITLE
Update to support NativeScript 8.x

### ISSUE THREAD

**Issue by jarrodwhitley** [NathanaelA/nativescript-orientation#54]
This version current uses `tns-core-modules`, it needs to be updated to use `@nativescript/core`.

**Comment by NathanaelA** [comment]
Several years back I moved most my plugins to ProPlugins.      ProPlugins has the supported versions of this plugin along with all the other fixes that were needed for NS 8 support.

Since, I no longer support this version of the plugin, if you want to provide a PR for this issue, I have no issue pushing a new version of the plugin with your PR.
